name: deploy
concurrency: testnet

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy-open-offchain:
    name: deployment
    runs-on: ubuntu-20.04
    environment: testnet
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy
        run: aws s3 sync ./src s3://www.hashstack.finance
