name: deploy
concurrency: testnet

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy-landing-page-staging:
    name: deployment
    runs-on: ubuntu-20.04
    environment: testnet
    steps:
      - uses: actions/checkout@v2

      # AWS IAM: starknet_codedeploy
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Generate Sitemap
        run: npx next-sitemap generate

      - name: Deploy
        # if deployment successful, you should find the site hosted at
        # http://www.hashstack.finance
        run: aws s3 sync --delete ./out s3://www.hashstack.finance

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: E1OQYS9UHZLSM0
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
